import type { InboxItem } from "@/lib/inbox/inbox-types";

/**
 * Operational inbox seed — Dropi / Dropea isolated.
 * Presentation for the priority queue until customer/country fields land in sync.
 * issueLabel / issueDetail are i18n keys under inbox.demo.*
 */
export const INBOX_ITEMS: readonly InboxItem[] = [
  {
    id: "DP-92744",
    supply: "dropi",
    customer: "Marta Silva",
    country: "Portugal",
    countryCode: "pt",
    phone: "+351912334455",
    total: 64.8,
    currency: "EUR",
    product: "Lume Watch",
    issueLabel: "inbox.demo.addressIncomplete",
    issueDetail: "inbox.demo.missingApartmentNumber",
    priority: "critical",
    carrier: "GLS",
    tracking: "PT998877",
    updatedAt: minutesAgo(18),
  },
  {
    id: "DP-92731",
    supply: "dropi",
    customer: "João Pereira",
    country: "Portugal",
    countryCode: "pt",
    phone: "+351918223344",
    total: 39.9,
    currency: "EUR",
    product: "Aura Lamp",
    issueLabel: "inbox.demo.waitingForReply",
    issueDetail: "inbox.demo.noResponseToLastMessage",
    priority: "waiting",
    carrier: "DPD Polska",
    tracking: "PT441122",
    updatedAt: minutesAgo(42),
  },
  {
    id: "DP-92718",
    supply: "dropi",
    customer: "Ana Costa",
    country: "Spain",
    countryCode: "es",
    phone: "+34611223344",
    total: 89.0,
    currency: "EUR",
    product: "Nova Chair",
    issueLabel: "inbox.demo.deliveryFailed",
    issueDetail: "inbox.demo.recipientUnavailable",
    priority: "critical",
    carrier: "DHL",
    tracking: "ES330011",
    updatedAt: hoursAgo(1),
  },
  {
    id: "DP-92705",
    supply: "dropi",
    customer: "Carlos Mendes",
    country: "Spain",
    countryCode: "es",
    phone: "+34622114455",
    total: 54.5,
    currency: "EUR",
    product: "Pulse Band",
    issueLabel: "inbox.demo.waitingForReply",
    issueDetail: "inbox.demo.followUpOverdue",
    priority: "waiting",
    carrier: "GLS Poland",
    tracking: "ES778899",
    updatedAt: hoursAgo(2),
  },
  {
    id: "DP-92690",
    supply: "dropi",
    customer: "Sofía Bianchi",
    country: "Italy",
    countryCode: "it",
    phone: "+393334455667",
    total: 72.0,
    currency: "EUR",
    product: "Ergo Stand",
    issueLabel: "inbox.demo.wrongAddress",
    issueDetail: "inbox.demo.postalCodeMismatch",
    priority: "critical",
    carrier: "InPost",
    tracking: "IT120045",
    updatedAt: hoursAgo(3),
  },
  {
    id: "DP-92681",
    supply: "dropi",
    customer: "Elena Cortés",
    country: "Spain",
    countryCode: "es",
    phone: "+34655443322",
    total: 48.2,
    currency: "EUR",
    product: "Air Fryer Mini",
    issueLabel: "inbox.demo.noResponse",
    issueDetail: "inbox.demo.confirmationPending",
    priority: "followup",
    carrier: "InPost",
    tracking: "ES550022",
    updatedAt: hoursAgo(4),
  },
  {
    id: "DP-92670",
    supply: "dropi",
    customer: "Lucía Ramírez",
    country: "Spain",
    countryCode: "es",
    phone: "+34622119988",
    total: 31.5,
    currency: "EUR",
    product: "Massage Gun",
    issueLabel: "inbox.demo.addressIncomplete",
    issueDetail: "inbox.demo.missingFloorDoor",
    priority: "critical",
    carrier: null,
    tracking: null,
    updatedAt: hoursAgo(5),
  },
  {
    id: "DP-92655",
    supply: "dropi",
    customer: "María Fernández",
    country: "Spain",
    countryCode: "es",
    phone: "+34611887766",
    total: 99.0,
    currency: "EUR",
    product: "Desk Mat XL",
    issueLabel: "inbox.demo.waitingForReply",
    issueDetail: "inbox.demo.askedForNewTimeSlot",
    priority: "waiting",
    carrier: "DHL",
    tracking: "ES909011",
    updatedAt: hoursAgo(6),
  },
  // Extra Dropi rows to support summary badges without inventing live sync
  ...Array.from({ length: 10 }, (_, index) => {
    const n = 92640 - index;
    const waiting = index % 2 === 0;
    return {
      id: `DP-${n}`,
      supply: "dropi" as const,
      customer: waiting ? `Client ${n}` : `Buyer ${n}`,
      country: index % 3 === 0 ? "Portugal" : "Spain",
      countryCode: index % 3 === 0 ? "pt" : "es",
      phone: index % 3 === 0 ? "+351910000000" : "+34600000000",
      total: 24 + index * 3.5,
      currency: "EUR",
      product: waiting ? "Support SKU" : "Ops SKU",
      issueLabel: waiting ? "inbox.demo.waitingForReply" : "inbox.demo.deliveryFailed",
      issueDetail: waiting
        ? "inbox.demo.noResponseToLastMessage"
        : "inbox.demo.carrierCouldNotDeliver",
      priority: (waiting ? "waiting" : "critical") as InboxItem["priority"],
      carrier:
        (["InPost", "DPD Polska", "DHL", "GLS Spain", "CTT"] as const)[index % 5] ??
        null,
      tracking: `TR${n}`,
      updatedAt: hoursAgo(7 + index),
    };
  }),
  // Dropea
  {
    id: "DR-44102",
    supply: "dropea",
    customer: "Andrés Ocampo",
    country: "Colombia",
    countryCode: "co",
    phone: "+573015558822",
    total: 32.5,
    currency: "EUR",
    product: "LED Strip 5m",
    issueLabel: "inbox.demo.wrongAddress",
    issueDetail: "inbox.demo.carrierReportedIncorrectAddress",
    priority: "critical",
    carrier: "TIPSA",
    tracking: "CO7781",
    updatedAt: minutesAgo(25),
  },
  {
    id: "DR-44088",
    supply: "dropea",
    customer: "Tomás Herrera",
    country: "Mexico",
    countryCode: "mx",
    phone: "+525533221199",
    total: 21.9,
    currency: "EUR",
    product: "Vacuum Sealer",
    issueLabel: "inbox.demo.waitingForReply",
    issueDetail: "inbox.demo.noConfirmationReceived",
    priority: "waiting",
    carrier: "Estafeta",
    tracking: "MX2201",
    updatedAt: hoursAgo(1),
  },
  {
    id: "DR-44071",
    supply: "dropea",
    customer: "Diego Salas",
    country: "Chile",
    countryCode: "cl",
    phone: "+56988776655",
    total: 96.2,
    currency: "EUR",
    product: "Dash Cam 4K",
    issueLabel: "inbox.demo.rescheduleRequested",
    issueDetail: "inbox.demo.customerAskedNextWeek",
    priority: "critical",
    carrier: "Chilexpress",
    tracking: "CL3344",
    updatedAt: hoursAgo(2),
  },
  {
    id: "DR-44050",
    supply: "dropea",
    customer: "Javier Ruiz",
    country: "Spain",
    countryCode: "es",
    phone: "+34644778899",
    total: 27.3,
    currency: "EUR",
    product: "Pet Remover",
    issueLabel: "inbox.demo.noResponse",
    issueDetail: "inbox.demo.followUpOverdue",
    priority: "followup",
    carrier: "Correos",
    tracking: "ES6611",
    updatedAt: hoursAgo(3),
  },
  {
    id: "DR-44033",
    supply: "dropea",
    customer: "Nicolás Vega",
    country: "Argentina",
    countryCode: "ar",
    phone: "+5491133445566",
    total: 45.0,
    currency: "EUR",
    product: "Mini Projector",
    issueLabel: "inbox.demo.packageRefused",
    issueDetail: "inbox.demo.returnedToWarehouse",
    priority: "critical",
    carrier: "OCA",
    tracking: "AR9090",
    updatedAt: hoursAgo(5),
  },
  {
    id: "DR-44012",
    supply: "dropea",
    customer: "Bruno Castillo",
    country: "Peru",
    countryCode: "pe",
    phone: "+51987654321",
    total: 19.5,
    currency: "EUR",
    product: "Phone Mount",
    issueLabel: "inbox.demo.waitingForReply",
    issueDetail: "inbox.demo.addressConfirmationPending",
    priority: "waiting",
    carrier: "Olva",
    tracking: "PE1122",
    updatedAt: hoursAgo(8),
  },
  {
    id: "DR-43990",
    supply: "dropea",
    customer: "Camila Duarte",
    country: "Brazil",
    countryCode: "br",
    phone: "+5511998877665",
    total: 64.8,
    currency: "EUR",
    product: "Wireless Earbuds",
    issueLabel: "inbox.demo.noResponse",
    issueDetail: "inbox.demo.messageSentYesterday",
    priority: "followup",
    carrier: "Correios",
    tracking: "BR5566",
    updatedAt: hoursAgo(10),
  },
];

function minutesAgo(minutes: number) {
  return new Date(Date.now() - minutes * 60_000).toISOString();
}

function hoursAgo(hours: number) {
  return new Date(Date.now() - hours * 3_600_000).toISOString();
}

export function inboxItemsForSupply(supply: InboxItem["supply"]): InboxItem[] {
  return INBOX_ITEMS.filter((item) => item.supply === supply);
}
