/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdsRouteImport } from './routes/ads'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as HelpRouteImport } from './routes/help'
import { Route as IntegracaoApiRouteImport } from './routes/integracao-api'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ProfitsRouteImport } from './routes/profits'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthGoogleRouteImport } from './routes/auth.google'
import { Route as AuthShopifyRouteImport } from './routes/auth.shopify'
import { Route as ConnectionsIndexRouteImport } from './routes/connections.index'
import { Route as ConnectionsDropeaRouteImport } from './routes/connections.dropea'
import { Route as ConnectionsDropiRouteImport } from './routes/connections.dropi'
import { Route as ConnectionsShopifyRouteImport } from './routes/connections.shopify'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as AuthShopifyCallbackRouteImport } from './routes/auth.shopify.callback'
import { Route as ApiPublicWebhooksOrdersRouteImport } from './routes/api/public/webhooks/orders'
import { Route as ApiPublicWebhooksShopifyRouteImport } from './routes/api/public/webhooks/shopify'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsRoute = AdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegracaoApiRoute = IntegracaoApiRouteImport.update({
  id: '/integracao-api',
  path: '/integracao-api',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfitsRoute = ProfitsRouteImport.update({
  id: '/profits',
  path: '/profits',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleRoute = AuthGoogleRouteImport.update({
  id: '/auth/google',
  path: '/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthShopifyRoute = AuthShopifyRouteImport.update({
  id: '/auth/shopify',
  path: '/auth/shopify',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsIndexRoute = ConnectionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConnectionsRoute,
} as any)
const ConnectionsDropeaRoute = ConnectionsDropeaRouteImport.update({
  id: '/dropea',
  path: '/dropea',
  getParentRoute: () => ConnectionsRoute,
} as any)
const ConnectionsDropiRoute = ConnectionsDropiRouteImport.update({
  id: '/dropi',
  path: '/dropi',
  getParentRoute: () => ConnectionsRoute,
} as any)
const ConnectionsShopifyRoute = ConnectionsShopifyRouteImport.update({
  id: '/shopify',
  path: '/shopify',
  getParentRoute: () => ConnectionsRoute,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OrdersRoute,
} as any)
const AuthShopifyCallbackRoute = AuthShopifyCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthShopifyRoute,
} as any)
const ApiPublicWebhooksOrdersRoute = ApiPublicWebhooksOrdersRouteImport.update({
  id: '/api/public/webhooks/orders',
  path: '/api/public/webhooks/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksShopifyRoute =
  ApiPublicWebhooksShopifyRouteImport.update({
    id: '/api/public/webhooks/shopify',
    path: '/api/public/webhooks/shopify',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ads': typeof AdsRoute
  '/analytics': typeof AnalyticsRoute
  '/connections': typeof ConnectionsRouteWithChildren
  '/help': typeof HelpRoute
  '/integracao-api': typeof IntegracaoApiRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRouteWithChildren
  '/pricing': typeof PricingRoute
  '/profits': typeof ProfitsRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/google': typeof AuthGoogleRoute
  '/auth/shopify': typeof AuthShopifyRouteWithChildren
  '/connections/dropea': typeof ConnectionsDropeaRoute
  '/connections/dropi': typeof ConnectionsDropiRoute
  '/connections/shopify': typeof ConnectionsShopifyRoute
  '/orders/$id': typeof OrdersIdRoute
  '/connections/': typeof ConnectionsIndexRoute
  '/auth/shopify/callback': typeof AuthShopifyCallbackRoute
  '/api/public/webhooks/orders': typeof ApiPublicWebhooksOrdersRoute
  '/api/public/webhooks/shopify': typeof ApiPublicWebhooksShopifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ads': typeof AdsRoute
  '/analytics': typeof AnalyticsRoute
  '/help': typeof HelpRoute
  '/integracao-api': typeof IntegracaoApiRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRouteWithChildren
  '/pricing': typeof PricingRoute
  '/profits': typeof ProfitsRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/google': typeof AuthGoogleRoute
  '/auth/shopify': typeof AuthShopifyRouteWithChildren
  '/connections/dropea': typeof ConnectionsDropeaRoute
  '/connections/dropi': typeof ConnectionsDropiRoute
  '/connections/shopify': typeof ConnectionsShopifyRoute
  '/orders/$id': typeof OrdersIdRoute
  '/connections': typeof ConnectionsIndexRoute
  '/auth/shopify/callback': typeof AuthShopifyCallbackRoute
  '/api/public/webhooks/orders': typeof ApiPublicWebhooksOrdersRoute
  '/api/public/webhooks/shopify': typeof ApiPublicWebhooksShopifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ads': typeof AdsRoute
  '/analytics': typeof AnalyticsRoute
  '/connections': typeof ConnectionsRouteWithChildren
  '/help': typeof HelpRoute
  '/integracao-api': typeof IntegracaoApiRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRouteWithChildren
  '/pricing': typeof PricingRoute
  '/profits': typeof ProfitsRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/google': typeof AuthGoogleRoute
  '/auth/shopify': typeof AuthShopifyRouteWithChildren
  '/connections/dropea': typeof ConnectionsDropeaRoute
  '/connections/dropi': typeof ConnectionsDropiRoute
  '/connections/shopify': typeof ConnectionsShopifyRoute
  '/orders/$id': typeof OrdersIdRoute
  '/connections/': typeof ConnectionsIndexRoute
  '/auth/shopify/callback': typeof AuthShopifyCallbackRoute
  '/api/public/webhooks/orders': typeof ApiPublicWebhooksOrdersRoute
  '/api/public/webhooks/shopify': typeof ApiPublicWebhooksShopifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ads'
    | '/analytics'
    | '/connections'
    | '/help'
    | '/integracao-api'
    | '/login'
    | '/onboarding'
    | '/orders'
    | '/pricing'
    | '/profits'
    | '/settings'
    | '/templates'
    | '/auth/callback'
    | '/auth/google'
    | '/auth/shopify'
    | '/connections/dropea'
    | '/connections/dropi'
    | '/connections/shopify'
    | '/orders/$id'
    | '/connections/'
    | '/auth/shopify/callback'
    | '/api/public/webhooks/orders'
    | '/api/public/webhooks/shopify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ads'
    | '/analytics'
    | '/help'
    | '/integracao-api'
    | '/login'
    | '/onboarding'
    | '/orders'
    | '/pricing'
    | '/profits'
    | '/settings'
    | '/templates'
    | '/auth/callback'
    | '/auth/google'
    | '/auth/shopify'
    | '/connections/dropea'
    | '/connections/dropi'
    | '/connections/shopify'
    | '/orders/$id'
    | '/connections'
    | '/auth/shopify/callback'
    | '/api/public/webhooks/orders'
    | '/api/public/webhooks/shopify'
  id:
    | '__root__'
    | '/'
    | '/ads'
    | '/analytics'
    | '/connections'
    | '/help'
    | '/integracao-api'
    | '/login'
    | '/onboarding'
    | '/orders'
    | '/pricing'
    | '/profits'
    | '/settings'
    | '/templates'
    | '/auth/callback'
    | '/auth/google'
    | '/auth/shopify'
    | '/connections/dropea'
    | '/connections/dropi'
    | '/connections/shopify'
    | '/orders/$id'
    | '/connections/'
    | '/auth/shopify/callback'
    | '/api/public/webhooks/orders'
    | '/api/public/webhooks/shopify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdsRoute: typeof AdsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ConnectionsRoute: typeof ConnectionsRouteWithChildren
  HelpRoute: typeof HelpRoute
  IntegracaoApiRoute: typeof IntegracaoApiRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  PricingRoute: typeof PricingRoute
  ProfitsRoute: typeof ProfitsRoute
  SettingsRoute: typeof SettingsRoute
  TemplatesRoute: typeof TemplatesRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthGoogleRoute: typeof AuthGoogleRoute
  AuthShopifyRoute: typeof AuthShopifyRouteWithChildren
  ApiPublicWebhooksOrdersRoute: typeof ApiPublicWebhooksOrdersRoute
  ApiPublicWebhooksShopifyRoute: typeof ApiPublicWebhooksShopifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads': {
      id: '/ads'
      path: '/ads'
      fullPath: '/ads'
      preLoaderRoute: typeof AdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integracao-api': {
      id: '/integracao-api'
      path: '/integracao-api'
      fullPath: '/integracao-api'
      preLoaderRoute: typeof IntegracaoApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profits': {
      id: '/profits'
      path: '/profits'
      fullPath: '/profits'
      preLoaderRoute: typeof ProfitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google': {
      id: '/auth/google'
      path: '/auth/google'
      fullPath: '/auth/google'
      preLoaderRoute: typeof AuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/shopify': {
      id: '/auth/shopify'
      path: '/auth/shopify'
      fullPath: '/auth/shopify'
      preLoaderRoute: typeof AuthShopifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections/': {
      id: '/connections/'
      path: '/'
      fullPath: '/connections/'
      preLoaderRoute: typeof ConnectionsIndexRouteImport
      parentRoute: typeof ConnectionsRoute
    }
    '/connections/dropea': {
      id: '/connections/dropea'
      path: '/dropea'
      fullPath: '/connections/dropea'
      preLoaderRoute: typeof ConnectionsDropeaRouteImport
      parentRoute: typeof ConnectionsRoute
    }
    '/connections/dropi': {
      id: '/connections/dropi'
      path: '/dropi'
      fullPath: '/connections/dropi'
      preLoaderRoute: typeof ConnectionsDropiRouteImport
      parentRoute: typeof ConnectionsRoute
    }
    '/connections/shopify': {
      id: '/connections/shopify'
      path: '/shopify'
      fullPath: '/connections/shopify'
      preLoaderRoute: typeof ConnectionsShopifyRouteImport
      parentRoute: typeof ConnectionsRoute
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/auth/shopify/callback': {
      id: '/auth/shopify/callback'
      path: '/callback'
      fullPath: '/auth/shopify/callback'
      preLoaderRoute: typeof AuthShopifyCallbackRouteImport
      parentRoute: typeof AuthShopifyRoute
    }
    '/api/public/webhooks/orders': {
      id: '/api/public/webhooks/orders'
      path: '/api/public/webhooks/orders'
      fullPath: '/api/public/webhooks/orders'
      preLoaderRoute: typeof ApiPublicWebhooksOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/shopify': {
      id: '/api/public/webhooks/shopify'
      path: '/api/public/webhooks/shopify'
      fullPath: '/api/public/webhooks/shopify'
      preLoaderRoute: typeof ApiPublicWebhooksShopifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ConnectionsRouteChildren {
  ConnectionsDropeaRoute: typeof ConnectionsDropeaRoute
  ConnectionsDropiRoute: typeof ConnectionsDropiRoute
  ConnectionsShopifyRoute: typeof ConnectionsShopifyRoute
  ConnectionsIndexRoute: typeof ConnectionsIndexRoute
}

const ConnectionsRouteChildren: ConnectionsRouteChildren = {
  ConnectionsDropeaRoute: ConnectionsDropeaRoute,
  ConnectionsDropiRoute: ConnectionsDropiRoute,
  ConnectionsShopifyRoute: ConnectionsShopifyRoute,
  ConnectionsIndexRoute: ConnectionsIndexRoute,
}

const ConnectionsRouteWithChildren = ConnectionsRoute._addFileChildren(
  ConnectionsRouteChildren,
)

interface OrdersRouteChildren {
  OrdersIdRoute: typeof OrdersIdRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersIdRoute: OrdersIdRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

interface AuthShopifyRouteChildren {
  AuthShopifyCallbackRoute: typeof AuthShopifyCallbackRoute
}

const AuthShopifyRouteChildren: AuthShopifyRouteChildren = {
  AuthShopifyCallbackRoute: AuthShopifyCallbackRoute,
}

const AuthShopifyRouteWithChildren = AuthShopifyRoute._addFileChildren(
  AuthShopifyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdsRoute: AdsRoute,
  AnalyticsRoute: AnalyticsRoute,
  ConnectionsRoute: ConnectionsRouteWithChildren,
  HelpRoute: HelpRoute,
  IntegracaoApiRoute: IntegracaoApiRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  OrdersRoute: OrdersRouteWithChildren,
  PricingRoute: PricingRoute,
  ProfitsRoute: ProfitsRoute,
  SettingsRoute: SettingsRoute,
  TemplatesRoute: TemplatesRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthGoogleRoute: AuthGoogleRoute,
  AuthShopifyRoute: AuthShopifyRouteWithChildren,
  ApiPublicWebhooksOrdersRoute: ApiPublicWebhooksOrdersRoute,
  ApiPublicWebhooksShopifyRoute: ApiPublicWebhooksShopifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
