import type { DropiFieldDefinition } from "@/lib/integrations/dropi/dropi-types";

/**
 * Fields accepted by Dropi order-update notifications (POST).
 * Core = official status event. Static = optional customer/order snapshot.
 */
export const DROPI_WEBHOOK_FIELDS: readonly DropiFieldDefinition[] = [
  {
    key: "order_id",
    label: "order_id",
    description: "Dropi order identifier (required)",
    templateVariable: "{{order_id}}",
    optional: false,
  },
  {
    key: "event_date",
    label: "event_date",
    description: "Timestamp of the status event (required)",
    optional: false,
  },
  {
    key: "status_name",
    label: "status_name",
    description: "Current Dropi status label",
    templateVariable: "{{status_name}}",
    optional: true,
  },
  {
    key: "details",
    label: "details",
    description: "Incident or status details from Dropi",
    templateVariable: "{{details}}",
    optional: true,
  },
  {
    key: "tracking_code",
    label: "tracking_code",
    description: "Carrier tracking code",
    templateVariable: "{{tracking_code}}",
    optional: true,
  },
  {
    key: "tracking_url",
    label: "tracking_url",
    description: "Tracking URL supplied by Dropi only — never generated by ELEVATE",
    templateVariable: "{{tracking_url}}",
    optional: true,
  },
  {
    key: "shipping_company",
    label: "shipping_company",
    description: "Carrier / shipping company name",
    templateVariable: "{{shipping_company}}",
    optional: true,
  },
  {
    key: "total",
    label: "total",
    description: "Order total as sent by Dropi",
    templateVariable: "{{total}}",
    optional: true,
  },
  {
    key: "shopify_order_id",
    label: "shopify_order_id",
    description: "Linked Shopify order ID when provided by Dropi",
    templateVariable: "{{shopify_order_id}}",
    optional: true,
  },
  {
    key: "customer_name",
    label: "customer_name",
    description: "Customer full name (static snapshot — kept across status-only updates)",
    templateVariable: "{{first_name}}",
    optional: true,
  },
  {
    key: "phone",
    label: "phone",
    description: "Customer phone for WhatsApp",
    templateVariable: "{{phone}}",
    optional: true,
  },
  {
    key: "email",
    label: "email",
    description: "Customer email when Dropi sends it",
    optional: true,
  },
  {
    key: "city",
    label: "city",
    description: "Shipping city",
    templateVariable: "{{city}}",
    optional: true,
  },
  {
    key: "postal_code",
    label: "postal_code",
    description: "Postal / ZIP code",
    templateVariable: "{{postal}}",
    optional: true,
  },
  {
    key: "address",
    label: "address",
    description: "Shipping address line",
    optional: true,
  },
  {
    key: "country",
    label: "country",
    description: "Shipping country",
    optional: true,
  },
  {
    key: "product_summary",
    label: "product_summary",
    description: "Product name / summary for templates",
    templateVariable: "{{product}}",
    optional: true,
  },
  {
    key: "currency",
    label: "currency",
    description: "Order currency (ISO 4217) when provided",
    optional: true,
  },
  {
    key: "source",
    label: "source",
    description: "Supply label (defaults to Dropi Pro when omitted)",
    optional: true,
  },
] as const;

export const DROPI_WEBHOOK_PATH = "/api/public/webhooks/orders";
